Add `.log` method to Log object
This fixes the following error when running `test/node/info.js`:

    TypeError: output.log is not a function
	at BoxParser.Box.printHeader (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7436:9)
	at BoxParser.Box.print (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7448:7)
	at ISOFile.print (/home/josephfrazier/workspace/mp4box.js/dist/mp4box.all.js:7467:18)
	at Object.<anonymous> (/home/josephfrazier/workspace/mp4box.js/test/node/info.js:10:25)
	at Module._compile (internal/modules/cjs/loader.js:678:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
	at Module.load (internal/modules/cjs/loader.js:589:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
	at Function.Module._load (internal/modules/cjs/loader.js:520:3)
	at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)

---------------------------------------------------------------

It's an alias for `.debug`, since they are aliased in Node/etc:

https://devdocs.io/node/console#console_console_debug_data_args